# Generated by Django 6.0.4 on 2026-04-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('business', 'Business')], default='home', max_length=10),
        ),
    ]
