# Generated by Django 6.0.4 on 2026-04-16 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispapp', '0002_packages_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_list_ref',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='full_content', to='ispapp.bloglist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='bloglist',
            name='preview_image',
            field=models.ImageField(upload_to='previews/'),
        ),
    ]
