# Generated by Django 6.0.4 on 2026-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispapp', '0003_blog_blog_list_ref_alter_blog_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
