# Generated by Django 6.0.4 on 2026-04-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispapp', '0004_alter_packages_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_heading',
            field=models.CharField(max_length=100),
        ),
    ]
