# Generated by Django 6.0.4 on 2026-04-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispapp', '0005_alter_blog_sub_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interested_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ispapp.packages'),
        ),
    ]
